### ISSUE TITLE
error with yaml front matter

### ISSUE THREAD

**Issue by javaporter** [javaporter/roots#2]
When I am currently running `roots watch` and I include a local (yaml front matter) for stuff like body class or title, it works fine. However, if I then shut down roots and start it back up, I get this error: 

```
compiling... ✘ Error: TypeError: /Users/pk/Sites/roots/views/layout.jade:9
    7|     meta(name='description', content='#{description}')
    8|     meta(name="viewport", content="width=device-width, initial-scale=1")
  > 9|     title #{post.title} | Company
    10|     != css()
    11| 
    12|   body(class='#{post.bodyClass}')

Cannot read property 'title' of undefined

Potentially unhandled rejection [5] TypeError: /Users/pk/Sites/roots/views/layout.jade:9
    7|     meta(name='description', content='#{description}')
    8|     meta(name="viewport", content="width=device-width, initial-scale=1")
  > 9|     title #{post.title} | Company
    10|     != css()
    11| 
    12|   body(class='#{post.bodyClass}')

Cannot read property 'title' of undefined
  at eval (<anonymous>:35:47)
  at eval (<anonymous>:69:22)
  at res (/Users/pk/Sites/roots/node_modules/jade/lib/index.js:219:38)
  at Object.exports.render (/Users/pk/Sites/roots/node_modules/jade/lib/index.js:349:43)
  at /usr/local/lib/node_modules/roots/node_modules/accord/lib/adapters/jade.js:37:31
  at compile (/usr/local/lib/node_modules/roots/node_modules/accord/lib/adapters/jade.js:70:15)
  at Jade._render (/usr/local/lib/node_modules/roots/node_modules/accord/lib/adapters/jade.js:35:14)
  at Jade.Adapter.render (/usr/local/lib/node_modules/roots/node_modules/accord/lib/adapter_base.js:122:19)
  at Jade.wrapper (/usr/local/lib/node_modules/roots/node_modules/accord/node_modules/lodash/index.js:3252:85)
  at tryCatchReject (/usr/local/lib/node_modules/roots/node_modules/when/lib/makePromise.js:845:30)
  at runContinuation1 (/usr/local/lib/node_modules/roots/node_modules/when/lib/makePromise.js:804:4)
  at Fulfilled.when (/usr/local/lib/node_modules/roots/node_modules/when/lib/makePromise.js:592:4)
  at Pending.run (/usr/local/lib/node_modules/roots/node_modules/when/lib/makePromise.js:483:13)
  at Scheduler._drain (/usr/local/lib/node_modules/roots/node_modules/when/lib/Scheduler.js:62:19)
  at Scheduler.drain (/usr/local/lib/node_modules/roots/node_modules/when/lib/Scheduler.js:27:9)
  at process._tickCallback (node.js:355:11)
```

**Comment by javaporter** [comment]
Not sure why, but if you delete app.production.coffee, this goes away
